/**Login section */
export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOADING_REQUEST="LOADING_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
/**Logout section */
export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";
/**Create section */
export const SIGNUP_REQUEST="SIGNUP_REQUEST";
export const SIGNUP_FAIL="SIGNUP_FAIL";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
